"""Change description column type to text

Revision ID: 28213b610efd
Revises: fea0862084db
Create Date: 2023-06-20 22:38:18.311635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28213b610efd'
down_revision = 'fea0862084db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
