"""Add image column to movie table

Revision ID: 3e9b47f06646
Revises: 71a2a0a53b18
Create Date: 2023-06-05 13:02:21.770488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9b47f06646'
down_revision = '71a2a0a53b18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('image', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'image')
    # ### end Alembic commands ###
