"""Add seats table and connect it with reservations

Revision ID: 71a2a0a53b18
Revises: d5f6fc84e18b
Create Date: 2023-06-04 16:54:16.816520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a2a0a53b18'
down_revision = 'd5f6fc84e18b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation_seat_association',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.PrimaryKeyConstraint('reservation_id', 'seat_id')
    )
    op.drop_constraint('uq_screening_seat_row', 'reservations', type_='unique')
    op.drop_column('reservations', 'seat_number')
    op.drop_column('reservations', 'row_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('row_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reservations', sa.Column('seat_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('uq_screening_seat_row', 'reservations', ['screening_id', 'seat_number', 'row_number'])
    op.drop_table('reservation_seat_association')
    op.drop_table('seats')
    # ### end Alembic commands ###
